sudo: false
language: ruby
rvm:
  - 2.5.1
  - 2.4.4
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
before_install: gem install bundler -v 1.16.1
cache: bundler
notifications:
  email:
    on_success: never
    on_failure: change
